{- BEHAVIOR : 6 -}
data Counting
  { Zero  : Counting
  | One   : Counting
  | Two   : Counting
  | Three : Counting
  | Four  : Counting
  | Five  : Counting
  | Six   : Counting
  | Seven : Counting
  | Eight : Counting
  | Nine  : Counting }

case Six
  { Zero  -> 0
  | One   -> 1
  | Two   -> 2
  | Three -> 3
  | Four  -> 4
  | Five  -> 5
  | Six   -> 6
  | Seven -> 7
  | Eight -> 8
  | Nine  -> 9 }
