{- BEHAVIOR : 5 -}
codata Stream a
  { Head : Stream a -> a
  , Tail : Stream a -> Stream a }

data Pair a b
  { Pair : a -> b -> Pair a b }

let fib = coiter { Head # -> x . case x { Pair y z -> y }
                 ; Tail # -> x . case x { Pair y z -> Pair z (y+z) }
                 } with (Pair 1 1)
in
cocase
[Head
[Tail
[Tail
[Tail
[Tail
[Tail
[Tail
[Tail
[Tail
[Tail
[Tail
[Tail
[Tail
[Tail
[Tail
[Tail
[Tail
[Tail
[Tail
[Tail
[Tail #]]]]]]]]]]]]]]]]]]]]]
fib
